SONGS = [
    "🎶 I'm in love with the shape of you \n We push and pull like a magnet do\n Although my heart is falling too \n I'm in love with your body \n And last night you were in my room \n And now my bedsheets smell like you \n Every day discovering something brand new 🎶  \n 🎶  I'm in love with your body \n Oh—I—oh—I—oh—I—oh—I \n I'm in love with your body \n Oh—I—oh—I—oh—I—oh—I \n I'm in love with your body \n Oh—I—oh—I—oh—I—oh—I \n I'm in love with your body 🎶 \n **-Shape of You**",
    "🎶 I've been reading books of old \n The legends and the myths \n Achilles and his gold \n Hercules and his gifts \n Spiderman's control \n And Batman with his fists \n And clearly I don't see myself upon that list 🎶 \n **-Something Just Like This **",
    "🎶 I don't wanna live forever \n 'Cause I know I'll be livin' in vain \n And I don't wanna fit wherever \n I just wanna keep callin' your name \n Until you come back home \n I just wanna keep callin' your name \n Until you come back home \n I just wanna keep callin' your name \n Until you come back home 🎶 \n **-I don't Wanna Live Forever **",
    "🎶 Oh, hush, my dear, it's been a difficult year \n And terrors don't prey on \n Innocent victims \n Trust me, darling, trust me darling \n It's been a loveless year \n I'm a man of three fears \n Integrity, faith and \n Crocodile tears \n Trust me, darling, trust me, darling 🎶 \n **-Bad Lier",
    "🎶 Walking down 29th and Park \n I saw you in another's arms \n Only a month we've been apart \n **You look happier** \n \n Saw you walk inside a bar \n He said something to make you laugh \n I saw that both your smiles were twice as wide as ours \n Yeah, you look happier, you do 🎶 \n **-Happier **",
    "🎶 I took the supermarket flowers from the windowsill \n I threw the day old tea from the cup \n Packed up the photo album Matthew had made \n Memories of a life that's been loved \n Took the get well soon cards and stuffed animals \n Poured the old ginger beer down the sink \n Dad always told me, 'don't you cry when you're down' \n But mum, there's a tear every time that I blink 🎶 \n **-Supermarket Flowers**",
    "🎶 And you and I we're flying on an aeroplane tonight \n We're going somewhere where the sun is shining bright \n Just close your eyes \n And let's pretend we're dancing in the street \n In Barcelona \n Barcelona \n Barcelona \n Barcelona 🎶 \n **-Barcelona **",
    "🎶 Maybe I came on too strong \n Maybe I waited too long \n Maybe I played my cards wrong \n Oh, just a little bit wrong \n Baby I apologize for it \n \n I could fall, or I could fly \n Here in your aeroplane \n And I could live, I could die \n Hanging on the words you say \n And I've been known to give my all \n And jumping in harder than \n Ten thousand rocks on the lake 🎶 \n **-Dive**",
    "🎶 I found a love for me \n Darling just dive right in \n And follow my lead \n Well I found a girl beautiful and sweet \n I never knew you were the someone waiting for me \n 'Cause we were just kids when we fell in love \n Not knowing what it was \n \n I will not give you up this time \n But darling, just kiss me slow, your heart is all I own \n And in your eyes you're holding mine 🎶 \n **-Perfect**",
    "🎶 I was born inside a small town, I lost that state of mind \n Learned to sing inside the Lord's house, but stopped at the age of nine \n I forget when I get awards now the wave I had to ride \n The paving stones I played upon, they kept me on the grind \n So blame it on the pain that blessed me with the life 🎶 \n **-Eraser**",
    "🎶 Say, go through the darkest of days \n Heaven's a heartbreak away \n Never let you go, never let me down \n Oh, it's been a hell of a ride \n Driving the edge of a knife. \n Never let you go, never let me down \n \n Don't you give up, nah-nah-nah \n I won't give up, nah-nah-nah \n Let me love you \n Let me love you 🎶 \n **-Let me Love You**",
    "🎶 I'll stop time for you \n The second you say you'd like me to \n I just wanna give you the loving that you're missing \n Baby, just to wake up with you \n Would be everything I need and this could be so different \n Tell me what you want to do \n \n 'Cause I know I can treat you better \n Than he can \n And any girl like you deserves a gentleman 🎶 **-Treat You Better**",
    "🎶 You're the light, you're the night \n You're the color of my blood \n You're the cure, you're the pain \n You're the only thing I wanna touch \n Never knew that it could mean so much, so much \n You're the fear, I don't care \n 'Cause I've never been so high \n Follow me through the dark \n Let me take you past our satellites \n You can see the world you brought to life, to life \n \n So love me like you do, lo-lo-love me like you do \n Love me like you do, lo-lo-love me like you do 🎶 \n **-Love me Like you Do**",
    "🎶 Spent 24 hours \n I need more hours with you \n You spent the weekend \n Getting even, ooh ooh \n We spent the late nights \n Making things right, between us \n But now it's all good baby \n Roll that Backwood baby \n And play me close \n \n 'Cause girls like you \n Run around with guys like me \n 'Til sundown, when I come through \n I need a girl like you, yeah yeah 🎶 \n **-Girls Like You**",
    "🎶 Oh, angel sent from up above \n You know you make my world light up \n When I was down, when I was hurt \n You came to lift me up \n Life is a drink and love's a drug \n Oh, now I think I must be miles up \n When I was a river dried up \n You came to rain a flood 🎶**-Hymn for the Weekend ** ",
    "🎶 I've known it for a long time \n Daddy wakes up to a drink at nine \n Disappearing all night \n I don’t wanna know where he's been lying \n I know what I wanna do \n Wanna run away, run away with you \n Gonna grab clothes, six in the morning, go 🎶 \n **-Runaway **",
    "🎶 You were the shadow to my light \n Did you feel us \n Another start \n You fade away \n Afraid our aim is out of sight \n Wanna see us \n Alive 🎶 \n **-Faded**",
    "🎶 It's been a long day without you, my friend \n And I'll tell you all about it when I see you again \n We've come a long way from where we began \n Oh I'll tell you all about it when I see you again \n When I see you again 🎶 \n **-See you Again**",
    "🎶 I can swallow a bottle of alcohol and I'll feel like Godzilla \n Better hit the deck like the card dealer \n My whole squad's in here, walking around the party \n A cross between a zombie apocalypse and big Bobby 'The \n Brain' Heenan which is probably the \n Same reason I wrestle with mania 🎶 \n **-Godzilla**",
    "🎶 Yeah, I'm gonna take my horse to the old town road \n I'm gonna ride 'til I can't no more \n I'm gonna take my horse to the old town road \n I'm gonna ride 'til I can't no more (Kio, Kio) 🎶 \n **-Old Town Road**",
    "🎶 Oh-oh, ooh \n You've been runnin' round, runnin' round, runnin' round throwin' that dirt all on my name \n 'Cause you knew that I, knew that I, knew that I'd call you up \n You've been going round, going round, going round every party in L.A. \n 'Cause you knew that I, knew that I, knew that I'd be at one, oh 🎶 \n **-Attention **",
    "🎶 This hit, that ice cold \n Michelle Pfeiffer, that white gold \n This one for them hood girls \n Them good girls straight masterpieces \n Stylin', wilin', livin' it up in the city \n Got Chucks on with Saint Laurent \n Gotta kiss myself, I'm so pretty \n \n I'm too hot (hot damn) \n Called a police and a fireman \n I'm too hot (hot damn) \n Make a dragon wanna retire man \n I'm too hot (hot damn) \n Say my name you know who I am \n I'm too hot (hot damn) \n And my band 'bout that money, break it down 🎶 \n **-Uptown Funk**",
    "🎶 Just a young gun with the quick fuse \n I was uptight, wanna let loose \n I was dreaming of bigger things \n And wanna leave my own life behind \n Not a yes sir, not a follower \n Fit the box, fit the mold \n Have a seat in the foyer, take a number \n I was lightning before the thunder \n \n Thunder, feel the thunder \n Lightning then the thunder \n Thunder, feel the thunder \n Lightning then the thunder \n Thunder, thunder 🎶 \n **-Thunder**",
    "🎶 Oh, love \n How I miss you every single day \n When I see you on those streets \n Oh, love \n Tell me there's a river I can swim that will bring you back to me \n 'Cause I don't know how to love someone else \n I don't know how to forget your face \n No, love \n God, I miss you every single day and now you're so far away \n So far away 🎶 \n **-So Far Away**",
    "🎶 And if you feel you're sinking, I will jump right over \n Into cold, cold water for you \n And although time may take us into different places \n I will still be patient with you \n And I hope you know 🎶 \n **-Cold Water**",
    "🎶 When you feel my heat \n Look into my eyes \n It's where my demons hide \n It's where my demons hide \n Don't get too close \n It's dark inside \n It's where my demons hide \n It's where my demons hide 🎶 \n **-Demons**",
    "🎶 Who do you love, do you love now? \n I wanna know the truth (whoa) \n Who do you love, do you love now? \n I know it's someone new \n You ain't gotta make it easy, where you been sleepin'? 🎶 \n **-Who do  Love? **",
    "🎶 Your touch is magnetic \n 'Cause I can't forget it \n (There's a power pulling me back to you) \n And baby I'll let it \n 'Cause you're so magnetic I get it \n (When I'm waking up with you, oh) 🎶 \n **-Magnetic**",
    "🎶 Girl my body don't lie, I'm outta my mind \n Let it rain over me, I'm rising so high \n Out of my mind, so let it rain over me \n \n Ay ay ay, ay ay ay let it rain over me \n Ay ay ay, ay ay ay let it rain over me 🎶 \n **-Rain over Me**",
    "🎶 I miss the taste of a sweeter life \n I miss the conversation \n I'm searching for a song tonight \n I'm changing all of the stations \n I like to think that we had it all \n We drew a map to a better place \n But on that road I took a fall \n Oh baby why did you run away? \n \n I was there for you \n In your darkest times \n I was there for you \n In your darkest night 🎶 \n **-Maps**",
    "🎶 I wish—I wish that I was bulletproof, bulletproof \n I wish—I wish that I was bulletproof, bulletproof \n (Bullet-bulletproof, bullet-bullet-bulletproof) \n I'm trippin' on my words and my patience \n Writing every verse in a cadence \n To tell you how I feel, how I feel, how I feel (Yeah) \n This is how I deal, how I deal, how I deal (Yeah) \n With who I once was, now an acquaintance \n Think my confidence (My confidence) is in the basement \n Tryin' to keep it real, keep it real, keep it real (Yeah) \n 'Cause I'm not made of steel, made of steel 🎶 \n **-Bulletproof**",
    "🎶 You won't find him down on Sunset \n Or at a party in the hills \n At the bottom of the bottle \n Or when you're tripping on some pills \n When they sold you the dream you were just 16 \n Packed a bag and ran away \n And it's a crying shame you came all this way \n 'Cause you won't find Jesus in LA \n And it's a crying shame you came all this way \n 'Cause you won't find Jesus in LA 🎶 \n **-Jesus in LA**",
    "Not in a mood to sing. Sorry!",
]

HARRY = [
    "**Aberto**",
    "**Accio**",
    "**Aguamenti**",
    "**Alohomora**",
    "**Avada Kedavra**",
    "**Colloportus**",
    "**Confringo**",
    "**Confundo**",
    "**Crucio**",
    "**Descendo**",
    "**Diffindo**",
    "**Engorgio**",
    "**Episkey**",
    "**Evanesco**",
    "**Expecto Patronum**",
    "**Finestra**",
    "**Expelliarmus**",
    "**Homenum Revelio**",
    "**Impedimenta**",
    "**Imperio**",
    "**Impervius**",
    "**Incendio**",
    "**Levicorpus**",
    "**Lumos**",
    "**Muffliato**",
    "**Obliviate**",
    "**Petrificus Totalus**",
    "**Priori Incantato**",
    "**Protego**",
    "**Reducto**",
    "**Rennervate**",
    "**Revelio**",
    "**Rictusempra**",
    "**Riddikulus**",
    "**Scourgify**",
    "**Sectumsempra**",
    "**Silencio**",
    "**Stupefy**",
    "**Tergeo**",
    "**Wingardium Leviosa**",
]

GOTT = [
    '`"The man who passes the sentence should swing the sword."`',
    '`"When the snows fall and the white winds blow, the lone wolf dies but the pack survives!"`',
    '`"The things I do for love!"`',
    '`"I have a tender spot in my heart for cripples, bastards and broken things."`',
    '`"Death is so terribly final, while life is full of possibilities."`',
    '`"Once you’ve accepted your flaws, no one can use them against you."`',
    '`"If I look back I am lost."`',
    '`"When you play the game of thrones, you win or you die."`',
    '`"I grew up with soldiers. I learned how to die a long time ago."`',
    '`"What do we say to the Lord of Death?\nNot Today!"`',
    '`"Every flight begins with a fall."`',
    '`"Different roads sometimes lead to the same castle."`',
    '`"Never forget what you are. The rest of the world will not. Wear it like armour, and it can never be used to hurt you."`',
    '`"The day will come when you think you are safe and happy, and your joy will turn to ashes in your mouth."`',
    '`"The night is dark and full of terrors."`',
    '`"You know nothing, Jon Snow."`',
    '`"Night gathers, and now my watch begins!"`',
    '`"A Lannister always pays his debts."`',
    '`"Burn them all!"`',
    '`"What do we say to the God of death?"`',
    '`"There\'s no cure for being a c*nt."`',
    '`"Winter is coming!"`',
    '`"That\'s what I do: I drink and I know things."`',
    '`"I am the dragon\'s daughter, and I swear to you that those who would harm you will die screaming."`',
    '`"A lion does not concern himself with the opinion of sheep."`',
    '`"Chaos isn\'t a pit. Chaos is a ladder."`',
    '`"I understand that if any more words come pouring out your c*nt mouth, I\'m gonna have to eat every f*cking chicken in this room."`',
    '`"If you think this has a happy ending, you haven\'t been paying attention."`',
    '`"If you ever call me sister again, I\'ll have you strangled in your sleep."`',
    '`"A girl is Arya Stark of Winterfell. And I\'m going home."`',
    "`\"Any man who must say 'I am the King' is no true King.\"`",
    '`"If I fall, don\'t bring me back."`',
    "`\"Lannister, Targaryen, Baratheon, Stark, Tyrell... they're all just spokes on a wheel. This one's on top, then that one's on top, and on and on it spins, crushing those on the ground.\"`",
    '`"Hold the door!`',
    '`"When people ask you what happened here, tell them the North remembers. Tell them winter came for House Frey."`',
    '`"Nothing f*cks you harder than time."`',
    '`"There is only one war that matters. The Great War. And it is here."`',
    '`"Power is power!"`',
    '`"I demand a trial by combat!"`',
    '`"I wish I was the monster you think I am!"`',
    "Never forget what you are. The rest of the world will not.Wear it like armor,\n and it can never be used to hurt you.",
    "There is only one thing we say to death: **Not today.**",
    "If you think this has a happy ending, you haven’t been **paying attention**.",
    "Chaos isn’t a pit. Chaos is a ladder.",
    "You know nothing, **Jon Snow**",
    "**Winter** is coming.",
    "When you play the **game of thrones**, you win or you die.",
    "I'm not going to **stop** the wheel, I'm going to **break** the wheel.",
    "When people ask you what happened here, tell them the **North remembers**. Tell them winter came for **House Frey**.",
    "When the snows fall and the white winds blow,\n the lone wolf dies, but the pack **survives**.",
]

GOTM = [
    "[To your teachers on failing you in all your papers confidently, every time...](https://telegra.ph/file/431d178780f9bff353047.jpg)",
    "[A shift from the mainstream darling, sweetheart, jaanu, and what not...](https://telegra.ph/file/6bbb86a6c7d2c4a61e102.jpg)",
    "[To the guy who's friendzone-ing you...](https://telegra.ph/file/8930b05e9535e9b9b8229.jpg)",
    "[When your friend asks for his money back...](https://telegra.ph/file/2df575ab38df5ce9dbf5e.jpg)",
    "[A bad-ass reply to who do you think you are?](https://telegra.ph/file/3a35a0c37f4418da9f702.jpg)",
    "[When the traffic police stops your car and asks for documents...](https://telegra.ph/file/52612d58d6a61315a4c3a.jpg)",
    "[ When your friend asks about the food he/she just cooked and you don't want to break his/her heart...](https://telegra.ph/file/702df36088f5c26fef931.jpg)",
    "[When you're out of words...](https://telegra.ph/file/ba748a74bcab4a1135d2a.jpg)",
    "[When you realize your wallet is empty...](https://telegra.ph/file/a4508324b496d3d4580df.jpg)",
    "[When shit is about to happen...](https://telegra.ph/file/e15d9d64f9f25e8d05f19.jpg)",
    "[When that oversmart classmate shouts a wrong answer in class...](https://telegra.ph/file/1a225a2e4b7bfd7f7a809.jpg)",
    "[When things go wrong in a big fat Indian wedding...](https://telegra.ph/file/db69e17e85bb444caca32.jpg)",
    "[A perfect justification for breaking a promise...](https://telegra.ph/file/0b8fb8fb729d157844ac9.jpg)",
    "[When your friend just won't stop LOL-ing on something silly you said...](https://telegra.ph/file/247fa54106c32318797ae.jpg)",
    "[When someone makes a joke on you...](https://telegra.ph/file/2ee216651443524eaafcf.jpg)",
    "[When your professor insults you in front of the class...](https://telegra.ph/file/a2dc7317627e514a8e180.jpg)",
    "[When your job interviewer asks if you're nervous...](https://telegra.ph/file/9cc147d0bf8adbebf164b.jpg)",
    "[When you're sick of someone complaining about the heat outside...](https://telegra.ph/file/9248635263c52b968f968.jpg)",
    "[When your adda is occupied by outsiders...](https://telegra.ph/file/ef537007ba6d9d4cbd384.jpg)",
    "[When you don't have the right words to motivate somebody...](https://telegra.ph/file/2c932d769ae4c5fbed368.jpg)",
    "[When the bouncer won't let you and your group of friends in because you're all under-aged...](https://telegra.ph/file/6c8ca79f1e20ebd04391c.jpg)",
    "[To the friend who wants you to take the fall for his actions...](https://telegra.ph/file/d4171b9bc9104b5d972d9.jpg)",
    "[When that prick of a bully wouldn't take your words seriously...](https://telegra.ph/file/188d73bd24cf866d8d8d0.jpg)",
    "[ When you're forced to go shopping/watch a football match with your partner...](https://telegra.ph/file/6e129f138c99c1886cb2b.jpg)",
    "[To the large queue behind you after you get the last concert/movie ticket...](https://telegra.ph/file/2423f213dd4e4282a31ea.jpg)",
    "[When your parents thought you'd fail but you prove them wrong...](https://telegra.ph/file/39cc5098466f622bf21e3.jpg)",
    "[A justification for not voting!](https://telegra.ph/file/87d475a8f9a8350d2450e.jpg)",
    "[When your partner expects you to do too many things...](https://telegra.ph/file/68bc768d36e08862bf94e.jpg)",
    "[When your friends cancel on the plan you made at the last minute...](https://telegra.ph/file/960b58c8f625b17613307.jpg)",
    "[For that friend of yours who does not like loud music and head banging...](https://telegra.ph/file/acbce070d3c52b921b2bd.jpg)",
]

BELLO = [
    '`"Underwater bubbles and raindrops are total opposites of each other."`',
    '`"If you buy an eraser you are literally paying for your mistakes."`',
    '`"The Person you care for most has the potential to destroy you the most."`',
    '`"If humans colonize the moon, it will probably attract retirement homes as the weaker gravity will allow the elderly to feel stronger."`',
    '`"Any video with “wait for it” in the title is simply too long."`',
    '`"Your age in years is how many times you’ve circled the Sun, but your age in months is how many times the Moon has circled you."`',
    '`"Biting your tongue while eating is a perfect example of how you can still screw up, even with decades of experience."`',
    '`"Saying that your home is powered by a wireless Nuclear fusion reactor that is 93 Million miles away sounds way cooler than just saying you have solar panels on your roof."`',
    '`"The most crushing feeling is when someone smiles at you on the street and you don’t react fast enough to smile back."`',
    '`"Teeth constantly require maintenance to prevent their decay when alive, and yet they manage to survive for thousands of years buried as fossils."`',
    '`"A folder is for things that you don\'t want to fold."`',
    '`"Waking up in the morning sometimes feels like resuming a shitty movie you decided to quit watching."`',
    '`"If everything goes smoothly, you probably won\'t remember today."`',
    '`"When you meet new people in real life, you unlock more characters for your dream world."`',
    '`"Maybe if they renamed sunscreen to “anti-cancer cream” more people would wear it."`',
    '`"200 years ago, people would never have guessed that humans in the future would communicate by silently tapping on glass."`',
    '`"Parents worry about what their sons download and worry about what their daughters upload."`',
    '`"It\'s crazy how you can be the same age as someone, but at a completely different stage in your life."`',
    "`\"When you think you wanna die, you really don't wanna die, you just don't wanna live like this.\"`",
    '`"Technically, no one has ever been in an empty room."`',
    '`"An onion is the bass player of food. You would probably not enjoy it solo, but you’d miss it if it wasn’t there."`',
    "`\"We run everywhere in videogames because we're too lazy to walk, but In real life we walk everywhere because we're too lazy to run.\"`",
    '`"Every single decision you ever made has brought you to read this sentence."`',
    "`\"The word 'quiet' is often said very loud.\"`",
    '`"Everybody wants you to work hard, but nobody wants to hear about how hard you work."`',
    '`"We brush our teeth with hair on a stick and brush our hair with teeth on a stick."`',
    '`"No one remembers your awkward moments but they’re too busy remembering their own."`',
    '`"Dumb people try to say simple ideas as complex as possible while smart people try to say complex ideas as simple as possible."`',
    "`\"Some people think they're better than you because they grew up richer. Some people think they're better than you because they grew up poorer.\"`",
    '`"The biggest irony is that computers & mobiles were invented to save out time!"`',
    '`"After honey was first discovered, there was likely a period where people were taste testing any available slime from insects."`',
    '`"You know you’re getting old when your parents start disappointing you, instead of you disappointing them."`',
    '`"Humans are designed to learn through experience yet the education system has made it so we get no experience."`',
    '`"By focusing on blinking, you blink slower... Same for breathing."`',
    '`"Drivers in a hurry to beat traffic usually cause the accidents which create the traffic they were trying to avoid."`',
    '`"Characters that get married in fiction were literally made for each other."`',
    '`"Babies are a clean hard drive that can be programmed with any language."`',
    "`\"There could be a miracle drug that cures every disease to man, that we'll never know about because it doesn't work on rats.\"`",
    "`\"Rhinos evolved to grow a horn for protection, but it's what's making them go extinct.\"`",
    '`"Maybe we don\'t find time travelers because we all die in 25-50 years."`',
    '`"Sleep is the trial version of death, It even comes with ads based on your activity."`',
    '`"The most unrealistic thing about Spy movies is how clean the air ventilation system is!"`',
    '`"In games we play through easy modes to unlock hard modes. In life we play through hard modes to unlock easy modes."`',
    '`"Silent people seem smarter than loud people, because they keep their stupid thoughts to themselves."`',
    '`"If Greenland actually turns green, we\'re all screwed."`',
    '`"If someone says clever things in your dream, it actually shows your own cleverness."`',
    '`"Famous movie quotes are credited to the actor and not the actual writer who wrote them."`',
    '`"No one actually teaches you how to ride a bicycle. They just hype you up until you work it out."`',
    '`"Ask yourself why the the brain ignores the second the."`',
    '`"You’ve probably forgot about 80% of your entire life and most of the memories you do remember are not very accurate to what actually happened."`',
    '`"It will be a lot harder for kids to win against their parents in video games in the future."`',
    '`"Everyone has flaws, if you don\'t recognize yours, you have a new one."`',
    '`"Raising a child is training your replacement."`',
    "`\"'O'pen starts with a Closed circle, and 'C'lose starts with an open circle.\"`",
    '`"There\'s always someone who hated you for no reason, and still does."`',
    '`"After popcorn was discovered, there must have been a lot of random seeds that were roasted to see if it would have the same effect."`',
    '`"The more important a good night\'s sleep is, the harder it is to fall asleep."`',
    '`"Blessed are those that can properly describe the type of haircut they want to a new stylist."`',
    "`\"Too many people spend money they haven't earned, to buy things they don't want, to impress people they don't like!\"`",
    '`"Theme park employees must be good at telling the difference between screams of horror and excitement."`',
    '`"6 to 30 feels more half-an-hour than 50 to 20"`',
    '`"Getting your password right on the last login attempt before lockout is the closest thing to disarming a bomb at the last minute that most of us will experience."`',
    '`"Listening to podcasts before bed is the adult version of story-time."`',
    '`"If all criminals stopped robbing then the security industry would fall in which they could then easily go back to robbing."`',
    '`"A ton of whales is really only like half a whale."`',
    '`"When you get old, the old you is technically the new you, and your young self is the old you."`',
    '`"You probably won\'t find many negative reviews of parachutes on the Internet."`',
    '`"We show the most love and admiration for people when they\'re no longer around to appreciate it."`',
    "`\"We've practiced sleeping thousands of times, yet can't do it very well or be consistent.\"`",
    '`"Humans are more enthusiastic about moving to another planet with hostile environment than preserving earth - the planet they are perfectly shaped for."`',
    "`\"The happiest stage of most people's lives is when their brains aren't fully developed yet.\"`",
    '`"The most effective alarm clock is a full bladder."`',
    '`"You probably just synchronized blinks with millions of people."`',
    '`"Since we test drugs on animals first, rat medicine must be years ahead of human medicine."`',
    '`"Night before a day off is more satisfying than the actual day off."`',
    '`"We put paper in a folder to keep it from folding."`',
    '`"Somewhere, two best friends are meeting for the first time."`',
    '`"Our brain simultaneously hates us, loves us, doesn\'t care about us, and micromanages our every move."`',
    '`"Being a male is a matter of birth. Being a man is a matter of age. But being a gentleman is a matter of choice."`',
    '`"Soon the parents will be hiding their social account from their kids rather than kids hiding their accounts from the parents."`',
    '`"Wikipedia is what the internet was meant to be."`',
    '`"A theme park is the only place that you can hear screams in the distance and not be concerned."`',
    '`"A wireless phone charger offers less freedom of movement than a wired one."`',
    "`\"If you repeatedly criticize someone for liking something you don't, they won't stop liking it. They'll stop liking you.\"`",
    '`"Somewhere there is a grandmother, whose grandson really is the most handsome boy in the world."`',
    '`"If someday human teleportation becomes real, people will still be late for work."`',
    '`"The first humans who ate crabs must have been really hungry to try and eat an armored sea spider"`',
    '`"Doing something alone is kind of sad, but doing it solo is cool af."`',
    '`"Your brain suddenly becomes perfect at proofreading after you post something."`',
    '`"There\'s always that one song in your playlist that you always skip but never remove."`',
    '`"Kids next century will probably hate us for taking all the good usernames."`',
    '`"Bubbles are to fish what rain is to humans."`',
    '`"The more people you meet, the more you realise and appreciate how well your parents raised you."`',
    '`"A comma is a short pause, a coma is a long pause."`',
    '`"Someday you will either not wake up or not go to sleep."`',
    '`"Bermuda Triangle might be the exit portal of this simulation."`',
    '`"If we put solar panels above parking lots, then our cars wouldn\'t get hot and we would have a lot of clean energy."`',
    '`"By faith Abraham, when he was called to go out into a place which he should after receive for an inheritance, obeyed; and he went out, not knowing whither he went.  <Hebrews 18>."`',
    '`"By faith Noah, being warned of God of things not seen as yet, moved with fear, prepared an ark to the saving of his house; by the which he condemned the world, and became heir of the righteousness which is by faith.  <Hebrews 17>."`',
    '`"These words spake Jesus, and lifted up his eyes to heaven, and said, Father, the hour is come; glorify thy Son, that thy Son also may glorify thee:  <John 11>."`',
    '`"As thou hast given him power over all flesh, that he should give eternal life to as many as thou hast given him.  <John 12>."`',
]

TIPS = [
    "`\"Before telling your landlord you're moving, ask them to fix anything broken that you're worried you might get charged for. They often will, and then when you move out they won't be able to take it out of your security deposit.\"`",
    '`"Walking before solving a problem improves your creativity by an average of 60%."`',
    '`"Wake up a little earlier than your alarm? Don’t go back to bed and wait for your alarm. Waking up naturally instead of to some sort of stimuli will help you get off to a better and healthier start to your day."`',
    '`"Act like your future self is a real person. So when you see a chore that needs to be done, you can say "I\'ll do this now to be nice to my future self". Helps motivate to get things done because you\'re doing work for someone you want to help."`',
    '`"Think of purchases as a percentage of your budget/account balance rather than their actual cost."`',
    '`"Counting on fingers is a vital part of learning math, and children that do it from an early age develop much better math skills than those who have been told not to."`',
    '`"There are just some things in life you can’t control or you’ll never know the real reason why. The only thing you can do is accept it and move on. Part of happiness is accepting the past happened or being proud of it."`',
    '`"Make a recording of your voice with a sweet message or telling a story. If anything happens to you, your loved ones will greatly appreciate being able to listen to your voice again."`',
    "`\"If someone is treating you to a meal and you're wondering how much you should spend, ask them what they're ordering to get a better idea of the range.\"`",
    '`"Never leave water bottles, reading glasses, or anything else that can focus light in a spot that could get direct sunlight. A significant number of house/vehicle fires happen every year because of this."`',
    '`"If you reach out to someone for help on a technical issue and they spend their valuable time helping you but are unable to resolve it, always try and let them know how it got resolved so they can help the next person with the same issue."`',
    '`"If you find information on the internet that you may need again in the future, print the page to a PDF digital file. There is no guarantee that the page will be available again in the future, and now you will have a digital copy for future reference."`',
    '`"If you want to learn another language, watch children’s shows in that language to pick up on it quicker."`',
    '`"If you want to separate some pdf pages without using any new software. you can open the pdf file in chrome then click on print then select custom pages option, and finally choose to save as pdf."`',
    '`"If you’re ever in the heat of an argument, always act like you’re being recorded. This helps you from saying things you don’t mean and could regret later."`',
    '`"Make music playlists during times in your life when good things are happening and you are experiencing good feelings. Then when you\'re down later in life listen to those playlists to instantly feel better, and feel those good emotions again."`',
    '`"When going on a first date, think in terms of "will I like them?" instead of "will they like me?""`',
    '`"When researching things to do for your next leisure travel. Include \<location\> tourism scam into your search. All tourist heavy areas will have their own scams. This should not dampen your excitement but heighten your knowledge so your vacation will be more enjoyable."`',
    '`"Just because you’ve know that person for years doesn’t mean you should stay friends with them. A toxic friend need to be cut out of your life."`',
    '`"Tired of all the ads in one of the free (offline) game apps you’re playing? Go to your settings and turn off the apps access to cellular data. Enjoy the ad free game play!"`',
    '`"Treat your monthly savings goal like a bill. At the end of the month, hold yourself accountable to \“pay it off\” like you would your rent or your utilities. This will keep you on track for your savings goals."`',
    '`"If you need to wait until your boss is in a good mood to ask for something as simple as time off, you\'re in a toxic work environment and you need to take steps to exit sooner than later."`',
    '`"When debating someone on a heated issue, start by looking for something to agree with them on. The rest of the conversation will be a lot less hostile if you establish common ground."`',
    '`"Record random conversations with your parents and grandparents. Someday hearing their voice may be priceless to you."`',
    "`\"If you're a student planning on your career, look up postings of your dream job, find the skills and qualifications you'll need, then work backwards from there.\"`",
    "`\"If someone asks how your weekend was, assume they're really wanting to tell you about theirs. Keep your answer short and enthusiastically ask about theirs. It'll make their day.\"`",
    '`"When traveling with a friend or family member, don’t be afraid to suggest breaking off to each do your own things for a day. Going solo can be enjoyable (eat/go wherever want at your own pace), plus it reduces you being sick of each other by the end of the trip."`',
    '`"If you’ve got some free time and you’re planning on spending it watching tv/playing video games, etc. make yourself go on a short walk or do some brief exercise beforehand. You’ll probably end up going longer than you planned and you’ll feel better about relaxing after."`',
    '`"When you get a new notebook, leave the first page blank. When you finish using the notebook, you can number the pages and use the first page as a table of contents."`',
    '`"Don’t delete old playlists if you can prevent it; years later you can listen and not only rediscover music you were into but also experience whatever emotion you had associated with your tunes at the time."`',
    '`"No matter how small the job is, wear correct masks/respirators/eye or ear protection. Your future self will thank you."`',
    '`"Getting angry with people for making mistakes doesn\'t teach them not to make mistakes, it just teaches them to hide them."`',
    "`\"When making conversation with someone you've just met, ask them what they've been listening to lately, rather than what their favorite kind of music is - it's fresh in their mind and they won't have to pick favorites on the spot.\"`",
    '`"Learn to do -- and enjoy -- things by yourself. You\'re going to miss out on a lot of fun if you keep waiting for someone else to accompany you."`',
    '`"If you want someone to really listen to you, then start the conversation with "I shouldn\'t be telling you this, but...""`',
    '`"Do you not like having bitter coffee but don\'t want to add sugar for dietary or other reasons? Add a pinch of salt instead, it removes the bitter taste while not making your coffee taste salty."`',
    '`"Don\'t choose a common sound for your alarm clock to wake up. If you hear your alarm clock sound any other time, you will get anxiety."`',
    '`"Keep your water bottle near you and your alarm far from you in the morning for a great start to the day!"`',
    '`"If you borrow money from someone, don’t let it get to the point that he/she has to ask for it back. It sucks for both. If you can’t repay now, show intent by paying what you can and keeping the other person posted often"`',
    '`"Don\'t brag about knowledge you just acquired, simply explain it. You will learn humility, plus people often like to learn new things."`',
    '`"If you have a favorite movie you’ve seen several (or hundreds) of times, try watching it with subtitles/closed captioning on. You might be surprised just how many lines you heard wrong or missed entirely."`',
    '`"Write down great ideas when you get them; do that right away. You think you will never forget them, but you almost always will."`',
    '`"If you’re not sure whether someone is waving at you or someone behind you, just smile at them. \n(It’ll save you the very awkward feeling of receiving a greeting meant for someone else.)"`',
    '`"If you want to offer a deep and memorable compliment, ask someone how they did something. It gives them the opportunity to tell their story, and shows your genuine interest."`',
    '`"Don’t hide the things that make you unique. If you smile a certain way or have any thing about you that is not normal, be confident with it. People will find it cute or attractive because it makes you special."`',
    '`"When someone only remove one ear pod to talk to you, they most probably don\'t want a lengthy conversation."`',
    "`\"If you haven't used your voice in a while (sleeping, lonely, etc) and suddenly need to take a phone call, hum for a few seconds prior. Your vocal cords won't let you down.\"`",
    '`"Open chip bags upside down. They\'ve been sitting upright most of their lives which makes the seasoning settle to the bottom of the bag."`',
    '`"If you tell people there is an invisible man in the sky that created the entire universe, most will believe you; if you tell them the paint is wet, most will touch it to be sure."`',
    '`"When asked online to confirm "I am not a robot", if you long press on the tick box and release, you will not be asked to complete the "click all store front" etc tests."`',
    '`"Buy yourself a good pillow. You use it every night and the difference between a good pillow and a stack of cheap ones is almost immediately noticeable."`',
    '`"If you want your man to win in this world, treat him as a king at home, the world by itself call you a queen!"`',
    '`"Be mindful of poorer friends when suggesting splitting the bill equally in a restaurant. Some people will choose cheaper options because they\'re on a budget."`',
    "When you are trying to resolve an issue where someone else made an error, put the focus on the error and not the person. Example of this: Instead of saying, \“You didn’t send the attachment,\” I say, \“The attachment didn’t come through, please try sending it again.",
    '`"Buy a small bottle of perfume you have never tried on before going for a vacation and use it for while you\'re there. At any point after your vacation, you get a sniff of it, it brings back those memories instantly. Because scents are among the most powerful memory triggers."`',
    "`\"If someone wishes you Merry Christmas and you don't celebrate Christmas, just say thank you. There's no need to tell them you don't celebrate. It just makes things awkward.\"`",
    '`"When trying to focus on something (writing, revising, reading) listen to music with no words. This allows you to block out unwanted sound and having no lyrics can stop you from being distracted."`',
    '`"If you are quitting a vice (smoking, drinking, etc.) treat yourself with the money you are saving. It makes quitting easier."`',
    '`"Someone who likes you will often automatically look at you when they laugh or find something funny."`',
    '`"Never shake spices over a hot pan. The steam will enter the bottle causing the spice to go hard."`',
    '`"When starting a new change in your life such as going to the gym or quitting smoking, avoid telling friends or family. Their positive feedback can give you a false feeling of accomplishment tricking you into thinking you have already succeeded which can hinder your efforts to change."`',
    '`"If you are composing an important message, do not enter the recipient until you have finished composing it so that you do not accidentally send an incomplete message."`',
    '`"If you are nervous walking into a new place with a group of people, make sure you are the first to the building. You can hold the door for everyone else making yourself look kind, yet you will be the last one in and can follow everyone elses lead."`',
    '`"If you\'re double checking a number or a sequence, read it backwards to avoid making the same mistake twice."`',
    '`"Take photos of your parents doing things they do every day. When you get older, they will bring back memories more than any posed pic ever could."`',
    "`\"If you're in a job interview and you're offered a glass of water, always accept. If you're asked a tough question, you can take a sip and get yourself some extra seconds to think of a response.\"`",
    "`\"If you make a mistake, admit to the mistake, apologize, and explain what steps you'll take to prevent it from happening again in the future. It's very hard for people to yell at you if you've done that.\"`",
    '`"Universities like MIT offer free online courses for subjects like Computer Science, Engineering, Psychology and more that include full lectures and exams."`',
    "`\"Treat another persons phone or computer like you would their diary. Don't even touch it unless they allow you to. It's always for the best.\"`",
    "`\"Don't undervalue yourself when deciding whether or not to apply for a new job. It's up to the person doing the hiring to determine if you are what they're looking for, and the only way to guarantee that you won't get the job is if you don't apply for it.\"`",
    '`"When drying clothes in the sun, turn them inside out so the colours don’t fade in the sunlight."`',
    '`"To listen to music on your phone via YouTube in the background, use the Chrome browser, go to the video, and request desktop site. This will allow you to listen anywhere on the phone."`',
    '`"Whenever your smoke alarm goes off, give your dog a treat. They\'ll associate the alarm with the treat; so when the alarm goes off for real, your dog will come right to you."`',
    '`"You never know what is taking place in a stranger\'s life. Try to be patient and passive if some seems to be "overreacting"."`',
    '`"Everybody is genious of its own. But if you judge a fish by its ability to climb a tree rather than swimming, she will felt whole life like dumb. So master your field and recognise it very well rather than going after the blind suspections."`',
    '`"Search a beautiful heart, not a beautiful face. Beautiful things are not always good, but good things are always beautiful."`',
    '`"It\'s better to cross the line and suffer the consequences than to just stare at the line for the rest of your life."`',
    '`"Rather than shushing someone who’s speaking too loudly, try just talking to them in a much quieter voice. They often pick up on the contrast in volume, and self-correct without feeling attacked."`',
    '`"If there are no chances for job growth or improvement - it\'s time to move on. You are worth more the more you learn. Otherwise you are getting paid less the more you know."`',
    '`"If you burn food to the bottom of a pot and can\'t scrub it out, put the pot back on the stove and boil water in it. It will loosen the burnt food and make it easier to clean."`',
    '`"When filling out applications online, make sure you copy responses which typically take a long time to write, and paste them to a text file. You never know when you could get a server timeout."`',
    '`"Being positive doesn’t mean we don’t get negative thoughts. It just means that we don’t allow those thoughts to control our life."`',
    "`\"If you share an 'inside joke' with a friend around other people, just let them know what it is even if they won't get it. People don't appreciate being excluded.\"`",
    '`"Never make fun of someone if they mispronounce a word. It means they learned it by reading."`',
    '`"If a service dog without a person approaches you, it means that the person is in need of help."`',
    '`"When taking a taxi ALWAYS get a receipt even if you don\'t need one. That way if you happen to accidentally leave a personal belonging behind you will have the company name and taxi number."`',
    "`\"If you're buying a home printer for occasional use, get a laser printer; they're more expensive up front but way more economical in the long run.\"`",
    '`"Go for that run, no one is looking at you, don\'t overthink it, do it!"`',
]

QT = [
    '`"Arrange them in descending order of importance – MONEY, LOVE, FAMILY, CAREER, FRIENDS."`',
    '`"If you had to change your name, what would your new name be, and why would you choose that name?"`',
    '`"What’s the most interesting thing you’ve read or seen this week?"`',
    '`"What scene from a TV show will you never forget?"`',
    '`"If you could become a master in one skill, what skill would you choose?"`',
    '`"What three words can describe you?"`',
    '`"If you had to delete one app from your phone, what would it be?"`',
    '`"Would you go out with me if I was the last person on earth?"`',
    '`"If you switched genders for the day, what would you do?"`',
    '`"If you could eat lunch with someone here. Who would you choose?"`',
    '`"If you were told you only had one week left to live, what would you do?"`',
    '`"What\'s number one item you would save from your burning house?"`',
    '`"If you could only text one person for the rest of your life, but you could never talk to that person face to face, who would that be?"`',
    '`"How many kids do you want to have in the future?"`',
    '`"Who in this group would be the worst person to date? Why?"`',
    '`"What does your dream boy or girl look like?"`',
    '`"What would be in your web history that you’d be embarrassed if someone saw?"`',
    '`"Do you sing in the shower?"`',
    '`"What’s the right age to get married?"`',
    '`"What are your top 5 rules for life?"`',
    '`"If given an option, would you choose a holiday at the beach or in the mountains?"`',
    '`"If you are made the president of your country, what would be the first thing that you will do?"`',
    '`"If given a chance to meet 3 most famous people on the earth, who would it be, answer in order of preference."`',
    '`"Have you ever wished to have a superpower, if so, what superpower you would like to have?"`',
    '`"Can you spend an entire day without phone and internet? If yes, what would you do?"`',
    '`"Live-in relation or marriage, what do you prefer?"`',
    '`"What is your favorite cuisine or type of food?"`',
    '`"What are some good and bad things about the education system in your country?"`',
    '`"What do you think of online education?"`',
    '`"What are some goals you have failed to accomplish?"`',
    '`"Will technology save the human race or destroy it?"`',
    '`"What was the best invention of the last 50 years?"`',
    '`"Have you travelled to any different countries? Which ones?"`',
    '`"Which sport is the most exciting to watch? Which is the most boring to watch?"`',
    '`"What’s the most addictive mobile game you have played?"`',
    '`"How many apps do you have on your phone?"`',
    '`"What was the last song you listened to?"`',
    '`"Do you prefer to watch movies in the theater or in the comfort of your own home?"`',
    '`"Do you like horror movies? Why or why not?"`',
    '`"How often do you help others? Who do you help? How do you help?"`',
    '`"What song do you play most often?"`',
    '`"Suggest a new rule that should be added in this group!"`',
    '`"What app on your phone do you think I should get?"`',
    '`"What website or app has completely changed your life for better or for worse?"`',
    '`"What isn’t real but you desperately wish it was?"`',
    '`"What thing do you really wish you could buy right now?"`',
    '`"If you could ban an admin from this group. Who would you prefer ?"`',
    '`"What would you do if someone left a duffle bag filled with $2,000,000 on your back porch?"`',
    '`"Who is the luckiest person you know?"`',
    '`"If you could visit someone\'s house in this group, who would it be ?"`',
    '`"What are you tired of hearing about?"`',
    '`"If you died today, what would your greatest achievement be?"`',
    '`"What method will you choose to kill yourself?"`',
    '`"What’s the best news you\'ve heard in the last 24 hours?"`',
    '`"What is the most important change that should be made to your country’s education system?"`',
    '`"Send your favourite sticker pack."`',
    '`"Send your favourite animated sticker pack."`',
    '`"Send your favourite video or gif."`',
    '`"Send your favourite emojies"`',
    '`"What’s something you misunderstood as a child and only realized much later was wrong?"`',
]

LOGIC = [
    '`"Underwater bubbles and raindrops are total opposites of each other."`',
    '`"If you buy an eraser you are literally paying for your mistakes."`',
    '`"The Person you care for most has the potential to destroy you the most."`',
    '`"If humans colonize the moon, it will probably attract retirement homes as the weaker gravity will allow the elderly to feel stronger."`',
    '`"Any video with ?wait for it? in the title is simply too long."`',
    '`"Your age in years is how many times you?ve circled the Sun, but your age in months is how many times the Moon has circled you."`',
    '`"Biting your tongue while eating is a perfect example of how you can still screw up, even with decades of experience."`',
    '`"Saying that your home is powered by a wireless Nuclear fusion reactor that is 93 Million miles away sounds way cooler than just saying you have solar panels on your roof."`',
    '`"The most crushing feeling is when someone smiles at you on the street and you don?t react fast enough to smile back."`',
    '`"Teeth constantly require maintenance to prevent their decay when alive, and yet they manage to survive for thousands of years buried as fossils."`',
    '`"A folder is for things that you don\'t want to fold."`',
    '`"Waking up in the morning sometimes feels like resuming a shitty movie you decided to quit watching."`',
    '`"If everything goes smoothly, you probably won\'t remember today."`',
    '`"When you meet new people in real life, you unlock more characters for your dream world."`',
    '`"Maybe if they renamed sunscreen to ?anti-cancer cream? more people would wear it."`',
    '`"200 years ago, people would never have guessed that humans in the future would communicate by silently tapping on glass."`',
    '`"Parents worry about what their sons download and worry about what their daughters upload."`',
    '`"It\'s crazy how you can be the same age as someone, but at a completely different stage in your life."`',
    "`\"When you think you wanna die, you really don't wanna die, you just don't wanna live like this.\"`",
    '`"Technically, no one has ever been in an empty room."`',
    '`"An onion is the bass player of food. You would probably not enjoy it solo, but you?d miss it if it wasn?t there."`',
    "`\"We run everywhere in videogames because we're too lazy to walk, but In real life we walk everywhere because we're too lazy to run.\"`",
    '`"Every single decision you ever made has brought you to read this sentence."`',
    "`\"The word 'quiet' is often said very loud.\"`",
    '`"Everybody wants you to work hard, but nobody wants to hear about how hard you work."`',
    '`"We brush our teeth with hair on a stick and brush our hair with teeth on a stick."`',
    '`"No one remembers your awkward moments but they?re too busy remembering their own."`',
    '`"Dumb people try to say simple ideas as complex as possible while smart people try to say complex ideas as simple as possible."`',
    "`\"Some people think they're better than you because they grew up richer. Some people think they're better than you because they grew up poorer.\"`",
    '`"The biggest irony is that computers & mobiles were invented to save out time!"`',
    '`"After honey was first discovered, there was likely a period where people were taste testing any available slime from insects."`',
    '`"You know you?re getting old when your parents start disappointing you, instead of you disappointing them."`',
    '`"Humans are designed to learn through experience yet the education system has made it so we get no experience."`',
    '`"By focusing on blinking, you blink slower... Same for breathing."`',
    '`"Drivers in a hurry to beat traffic usually cause the accidents which create the traffic they were trying to avoid."`',
    '`"Characters that get married in fiction were literally made for each other."`',
    '`"Babies are a clean hard drive that can be programmed with any language."`',
    "`\"There could be a miracle drug that cures every disease to man, that we'll never know about because it doesn't work on rats.\"`",
    "`\"Rhinos evolved to grow a horn for protection, but it's what's making them go extinct.\"`",
    '`"Maybe we don\'t find time travelers because we all die in 25-50 years."`',
    '`"Sleep is the trial version of death, It even comes with ads based on your activity."`',
    '`"The most unrealistic thing about Spy movies is how clean the air ventilation system is!"`',
    '`"In games we play through easy modes to unlock hard modes. In life we play through hard modes to unlock easy modes."`',
    '`"Silent people seem smarter than loud people, because they keep their stupid thoughts to themselves."`',
    '`"If Greenland actually turns green, we\'re all screwed."`',
    '`"If someone says clever things in your dream, it actually shows your own cleverness."`',
    '`"Famous movie quotes are credited to the actor and not the actual writer who wrote them."`',
    '`"No one actually teaches you how to ride a bicycle. They just hype you up until you work it out."`',
    '`"Ask yourself why the the brain ignores the second the."`',
    '`"You?ve probably forgot about 80% of your entire life and most of the memories you do remember are not very accurate to what actually happened."`',
    '`"It will be a lot harder for kids to win against their parents in video games in the future."`',
    '`"Everyone has flaws, if you don\'t recognize yours, you have a new one."`',
    '`"Raising a child is training your replacement."`',
    "`\"'O'pen starts with a Closed circle, and 'C'lose starts with an open circle.\"`",
    '`"There\'s always someone who hated you for no reason, and still does."`',
    '`"After popcorn was discovered, there must have been a lot of random seeds that were roasted to see if it would have the same effect."`',
    '`"The more important a good night\'s sleep is, the harder it is to fall asleep."`',
    '`"Blessed are those that can properly describe the type of haircut they want to a new stylist."`',
    "`\"Too many people spend money they haven't earned, to buy things they don't want, to impress people they don't like!\"`",
    '`"Theme park employees must be good at telling the difference between screams of horror and excitement."`',
    '`"6 to 30 feels more half-an-hour than 50 to 20"`',
    '`"Getting your password right on the last login attempt before lockout is the closest thing to disarming a bomb at the last minute that most of us will experience."`',
    '`"Listening to podcasts before bed is the adult version of story-time."`',
    '`"If all criminals stopped robbing then the security industry would fall in which they could then easily go back to robbing."`',
    '`"A ton of whales is really only like half a whale."`',
    '`"When you get old, the old you is technically the new you, and your young self is the old you."`',
    '`"You probably won\'t find many negative reviews of parachutes on the Internet."`',
    '`"We show the most love and admiration for people when they\'re no longer around to appreciate it."`',
    "`\"We've practiced sleeping thousands of times, yet can't do it very well or be consistent.\"`",
    '`"Humans are more enthusiastic about moving to another planet with hostile environment than preserving earth - the planet they are perfectly shaped for."`',
    "`\"The happiest stage of most people's lives is when their brains aren't fully developed yet.\"`",
    '`"The most effective alarm clock is a full bladder."`',
    '`"You probably just synchronized blinks with millions of people."`',
    '`"Since we test drugs on animals first, rat medicine must be years ahead of human medicine."`',
    '`"Night before a day off is more satisfying than the actual day off."`',
    '`"We put paper in a folder to keep it from folding."`',
    '`"Somewhere, two best friends are meeting for the first time."`',
    '`"Our brain simultaneously hates us, loves us, doesn\'t care about us, and micromanages our every move."`',
    '`"Being a male is a matter of birth. Being a man is a matter of age. But being a gentleman is a matter of choice."`',
    '`"Soon the parents will be hiding their social account from their kids rather than kids hiding their accounts from the parents."`',
    '`"Wikipedia is what the internet was meant to be."`',
    '`"A theme park is the only place that you can hear screams in the distance and not be concerned."`',
    '`"A wireless phone charger offers less freedom of movement than a wired one."`',
    "`\"If you repeatedly criticize someone for liking something you don't, they won't stop liking it. They'll stop liking you.\"`",
    '`"Somewhere there is a grandmother, whose grandson really is the most handsome boy in the world."`',
    '`"If someday human teleportation becomes real, people will still be late for work."`',
    '`"The first humans who ate crabs must have been really hungry to try and eat an armored sea spider"`',
    '`"Doing something alone is kind of sad, but doing it solo is cool af."`',
    '`"Your brain suddenly becomes perfect at proofreading after you post something."`',
    '`"There\'s always that one song in your playlist that you always skip but never remove."`',
    '`"Kids next century will probably hate us for taking all the good usernames."`',
    '`"Bubbles are to fish what rain is to humans."`',
    '`"The more people you meet, the more you realise and appreciate how well your parents raised you."`',
    '`"A comma is a short pause, a coma is a long pause."`',
    '`"Someday you will either not wake up or not go to sleep."`',
    '`"Bermuda Triangle might be the exit portal of this simulation."`',
    '`"If we put solar panels above parking lots, then our cars wouldn\'t get hot and we would have a lot of clean energy."`',
    "`Do You Know, Some Mosquitos Became Ghosts, When you *Killed* Them...`",
    "`Do You Know, Mosquitoes has Teleportation Power...`",
    "`Do You Know, When you see a bearded Goat, that means you juat saw a *Smarter Goat* than YOU....`",
    "`Do You Know, when You give some ruppess to a Bus Conductor, He will give You a Piece of Paper, *Called Ticket*...`",
    "`Do You Know, Bus are called Bus, Because they are Bus....`",
    "`Do You Know, There's a Huge Difference between *Cartoon amd Anime*...`",
    "`Do You Know, We can't see Ghosts But Ghosts Can see Us...`",
]

SNOW = [
    "Never forget what you are. The rest of the world will not.Wear it like armor,\n and it can never be used to hurt you.",
    "There is only one thing we say to death: **Not today.**",
    "If you think this has a happy ending, you haven’t been **paying attention**.",
    "Chaos isn’t a pit. Chaos is a ladder.",
    "You know nothing, **Jon Snow**",
    "**Winter** is coming.",
    "When you play the **game of thrones**, you win or you die.",
    "I'm not going to **stop** the wheel, I'm going to **break** the wheel.",
    "When people ask you what happened here, tell them the **North remembers**. Tell them winter came for **House Frey**.",
    "When the snows fall and the white winds blow,\n the lone wolf dies, but the pack **survives**.",
]

SHAYRI = [
    "কিতনা খুসনুমা হোগা,\nওহ মেরি মৈত কা মানজার\nযব মুঝে থুকরানে ওয়ালে\nখুদ মুঝে পান কে লিয়ে,\nআনসু বাহায়াঙ্গে!!!☺️\n\n\n️ {}",
    "জিন্দেগি মে বার বার\nকোই সাহারা না মিলতা,\n\nবার বার কোই\nপেয়ার সে পেয়ারা না মিলতা,\n\nজো পাস হ্যায় উসি সম্বল কে রাখা,\nকিউকি কোই খু জায়ে তো\n\n\n*ফির দোবারা মিল্টা...**☺️\n\n\n✍️ {}",
    "মাঝে মাঝে বলতাম যে\nআজ শুরু হয়ে গেছি...\n\nআমাদের সাথে কথা না বলার জন্য অজুহাত তৈরি করেছি...\n\nকিভাবে ধন্যবাদ জানাবো\nআমি বুঝতে পারছি না...\n\ nআমার হৃদয় বড় হয়েছে \n** এই জীবন থেকে...*\n\n\n✍️{}",
    "তেরি খুবসুরতি কি তারিফ \nম্যায় আব কেয়া লিখু\n\n\nকুছ খুবসুরাত লাফজন কি তালাশ \nআব ভি হ্যায় মুঝে🙂\n\n\n✍️{}",
    "ম্যায় উসকা হো নাহি সাকতা,\nও মেরি হো নাহি শক্তি\n\nওহ আয়ে লাখ খোয়াবোন ম্যায়,\nসপনা সাচ হো নাহি সাক্ত\n\nমেরে নাজদেক হো কার ভি,\nনাহি হ্যায় ওও সাথ মেরে\n\nউসে নিন্দ না আতি ,\nইয়াহা ম্যায় সো নাহি সাকতা\n\nমহব্বত কা জো রিশতা হ্যায়,\nনা জানে কইসা রিশতা হ্যায়\n\nমেরা হো কে ভি কোই,\n**মেরা হো নাহি সাকতা!!!**\n\n\n ️{}",
    "দুখ ইয়ে নাহি,\nকে কোন আপনা না....\n\nদুখ ইয়ে হ্যায় কে\nকিসি নে\n\n\n**আপনা বানা কর চোর দিয়া**🙂💔\n\n\n✍️{} ",
    "একবার ভুল করে,\nআমি বলতাম যে আমরা অন্য কারো,\nআল্লাহর শপথ\nআমরা তোমার ছায়া থেকে দূরে থাকি"
    "দোস্তি নিভাতে নিভাতে \nউস সে মহব্বত সি হো গায়ে\n\nগাম হি মিলে সাহি \nপার চাহাত সি হো গায়ে\n\nকারতে দ্য জো বাতাইন \nরাত রাত ভর\nআজ উন সে বাত কারনে কি খোয়াহিশ সি হো গায়ে\n\nজি নাহি সাকতে আব উস কে বিন\n**উস কে সাথ রেহনে কি আদত সি হো গেই**\n\n\n✍️{}",
    "তেরে দেদার কে মিথ্যা আতে হ্যায়\nতেরি গালিওঁ মে...\n\nওয়ারনা আওয়ারগি কে মিথ্যে বলে\nপুর সেহের পড়ে হ্যায়🙂\n\n\n✍️{}",
    "বস আখির বার তেরে পেয়ার কো মেহসুস কারলুন\n\nলৌত কে ফির কাভি তেরে গালিয়ুন মে না আউঙ্গা\n\nআপনি বারবাদ মহব্বত কা জানাজা লেকার\n**তেরি দুনিয়া সে বহুত দূর চালা জাউঙ্গা****\n\n n\n\n\n\n\n\n\n\n\n\n\n\" {}",
    "ভেদ কি আদত নহি মুঝে\nথোদে মে জিনা শিখ লিয়া হুমনে\n\nদো দোস্ত হ্যায়, চাঁদ দুয়ে হ্যায়\nবাস ইন খুসিয়ুন কো\nগালে লাগা লিয়া হুমনে🙂\n\n\n✍️{}",
    "বন্ধুত্বের মতো সুন্দর একটা সম্পর্ককে কবর দিয়েছো।\nএখন কবর দেওয়া হোক।\n\nএখন আমার মধ্যে কোনো আবেগ অবশিষ্ট নেই\nআমি মরে গেছি\nএখন তুমি আমাকে কবর দিয়ে রেখেছ\n\n\n✍️{}"
    "আপনি যদি কিছু মনে না করেন তাহলে বলুন???\n\nআমাদেরও খারাপ লাগছে!!!!\n\n\n✍️{}",
    "আমি কেন তোমার ভাবনায় হারিয়ে যেতে থাকি\n\nআমি পাগল নই \nআমি প্রতি মুহূর্তে তোমার জন্য কাঁদি!\n\n\n✍️{}",
    "না **রাজ** হল... জীবন,...\nনা ** রাগ**... জীবন,...\nযাই হোক না কেন,........\n সেটা হল **আজ**....... জীবন\n\n\n✍️{}",
    "যখন তুমি বুঝো না,\nআমি নিজেকে কতো বুঝিয়েছি\n\nতুমি কখনো বুঝবে না\n\n\n✍️{}",
    "কিসি নে ইউন হি পুছ লিয়া হামসে\nকি দর্দ কি কিমাত কেয়া হ্যায়,\nহমনে হানস্তে হুয়ে কাহা\nপাতা না\n\n**কুছ আপনে মুফ্ট মে দে গেয়ে**\n\n\n✍️{}",
    "রেখাও কা খেল সে সারা\nকেয়া করে তাকদীর কা মারা\n\nজিস কদর উসকি কদর কি..\n**উস কদর বেকদর হুভে হাম**\n\n\n✍️{}",
    "কেন আপনারা সবাই আমাকে আমার দিকে টানছেন,\nতুমি কি, তুমি কে, কেন তুমি আমার কাছে এত গুরুত্বপূর্ণ\nকেন তুমি ছায়ার মতো আমার পাশে আছো,\n\nতুমি যদি এমনই হও তাহলে \nতুমি এত দূরে আমার থেকে দূরে থাকলেও\n**কেন আছে\n\n\n✍️{}",
    "চোখ সেই দৃষ্টিকে লক্ষ্য করে না\nকাউকে এতটা ভালো লাগে না \n\nআমি তোমাকে শুধু সেই চোখ দিয়ে দেখেছি\nযে দৃষ্টি দিয়ে তুমি দেখতে পাও না\n\n\n✍️{}",
    "তেরি মুশকুরাহত মেরি পহেচান হে\nতেরি খুশি মেরি শান হে\n\nকুছ ভি নাহি সে মেরি জিন্দগি মে\nইতনা স্মাজ লে বাস তু মেরি জান হে\n\n\n✍️{}",
    "💞💞💞💞💞💞💞💞💞💞\n\nআমার ভালোবাসা খুব সূক্ষ্ম, রাখো...,\n\n\nআঙ্গুল দিয়ে ধরো না...\nএটা তোমার হাতের তালুতে রাখো... .,\n \n💞💞💞💞💞💞💞💞💞💞\n\n\n✍️{}",
    "তোমার ভালোবাসার যুদ্ধে,\nআমরা হাসি নিয়ে দাঁড়িয়েছিলাম,\n\nআমরা তরবারি দিয়ে রক্ষা পেয়েছি,\nতোমার হাসিতে কেটে গেছে।\n\n\n✍️{}",
    "💖 চোখে দেখা হয়...,,\nভালোবাসার গভীরতা।\n\nকথায় লুকিয়ে..,,\nঅনেক একাকীত্ব...💖⚡😘\n\n\n✍️{}"
    "ধড়কান ইয়ে কেহতি হ্যায়।\nদিল তেরে বিন ধড়কে না।\nএক তু হি ইয়ার মেরা।\nমুজকো কেয়া দুনিয়া সে লেনা\n\n\n️ {}",
    "খুদ নাহি জানতে কিতনে পেয়ারে হো আপ।\nজান হো হামারি পার জান সে প্যায়ারি হো আপ।\nদুরিওঁ কে হোন সে কোই ফার্ক নাহি পড়তা।\nকাল ভি হামারে দ্য অর আজ ভি হামারি হো আপ\n\n\n✍️ {} ",
    "সমন্দর কিনারে বাইতে হ্যায়।\nকভি তো লেহের আসবে।\nকিসমাত বদলে ইয়া না বাদল।\nগান্ড থেকে ঝুল যায়েগি।\n\n\n✍️ {}",
    "মেরে দিল কে ইয়ে টুকদে হ্যায়।\nনিগাহো সে চুনু ইয়ারা।\nমোহাবত্ত কি কাহানি হ্যায়।\nমোহাবত্ত সে সুনো ইয়ারা।\n\n\n✍️ {}",
    "কৌনসা জখম থা জো তাজা না থা।\nইটনা গাম মিলেগা আন্দাজা না থা।\nআপ কি ঝিল সি আঁখোঁ কা কেয়া কাসুর।\nডুবনে ওয়ালে কো হি গেহরাই কা আন্দাজা না থা\n\n\n✍️ {}",
    "বহতে হুয়ে দুরিয়া কো কেয়া মোদেগা কোই।\nতুতে হুয়ে শিশে কো কেয়া জোদেগা কোই।\nচলো ফির সে দিল লাগাকে দেখে হ্যায়।\nআব ইস টুতে হুয়ে দিল কো কেয়া তোদেগা কোই\n\n\n✍️ {}",
    "দিল কো জলতে হ্যায় হাম দিয়ে কি তারাহ,\nতেরি জিন্দেগি ম্যায় রোশনি লেন কে লিয়ে,\nলে লেট হ্যায় হর কাতোঁ কো আপনি জিন্দেগি মে,\nবস তেরি রাহোন ম্যায় ফুল ভাবনে কে লিয়ে\n\n\n✍️{}",
    "প্যাসে কো এক কাটরা পানি কাফি হ্যায়।\nইশক মে চার পাল কি জিন্দগানি কাফি হ্যায়।\nদুবনে কো সমন্দার মে জায়েন কাহান।\nআপকি আঁখ সে তপকা ভো পানি কাফি হ্যায়।\n\n\n✍️ {}",
    "হামনে তো বাসস দোস্ত কো হাইবেওয়াফা সমঝ থা...\nইয়াহান সাচ্চা প্যায়ার ভি সাথ না দিয়া🥱🥱\n\n\n✍️ {}",
    "ভালোবাসা মৃত্যুর দিকে নিয়ে যায় \nঅথবা জীবিত মৃতের দিকে \n\n\n✍️ {}",
    "বাতেন তু কাভি ইয়ে না ভুলনা.....\nকোই তেরে কারান হ্যায়..এমআরআর আরহা \n\n\n✍️ {}",
    "এ দোস্ত তেরে যায়ে লগ কো কাট কে ফেক ডাঙ্গে হম\nমেরি তরফ এ তার তুফান কো তেরি তরফ ভেজ ডাঙ্গে হম...\nলেখিন সুর জো সাথ চোরদা হামারা......\nকেএসএম সে বদনাম করকে তুঝে নিয়া দোস্ত... ..\nধুন্ধ ল্যাঙ্গে হুম🥱🥱🥱🥱\n\n\n✍️ {}",
    "বদে আজিব হ্যায় ইয়ে জিন্দেগি কে রাস্তে.........\nআনজানে মোড পে লোগ মিল জাতে হ্যায়...খুদ কো আপনা বিটিএ কে.....চোরা যায়ে হ্যায়...\n. কেআরটিই হ্যায়। হা বাত (জিন্দেগি ভর সাথ রাহেঙ্গে) সুদ খাটম হবে প্রর......জিন্দা লাশ বিএনএ যায় হা🥱🥱🥱\n\n\n✍️ {}",
    "দিল জাইসা থা ওয়াইসা হি রে জাতা......\nজিতে দর্দ থেই ইউটিনে কাফি থেয়.......\nজিন্দেগি আপ মে আকে অর তদপা দিয়া.........\nমিল্লা কেয়া উ বদনাম krke ....জিন্দা লাশ...... DIYA🙃🙃\n\n\n✍️ {}",
    "দর্দ সে ইস কদর দোস্তি হো গে.......\nজিন্দেগি বেদারদ সি হো গে.......\nজাল গে ও আশিয়ানা.......জো কখনো বন হি না থা.... ..\nরোশনি তো চোরদো...........\nঘর মে জো মোমাবাত্তি থি ও ভি খাতম হো গে............🥱🥱\n\n\n✍️ { }",
    "জিন্দেগি বরবাদ হ্যায়...... জিন্দেগি সে পেয়ার না করো.......\nহো রাত তো দিন কা ইন্তেজার না করো.......\nও পল্ল ভি আসেগা....জিস পাল কা ইন্তেজার না হো আকো.....\nPRRR uspe kabhi itbaar na karo........🥱🥱\n\n\n✍️ {}",
    "দর্দ কে সাথ রাতে হুয়ে ভি দোস্তি নহি হুই\nজিন্দেগি বেদর্দ সি হোতে হুয়ে ভি নহি হুই\nআশিয়ানা তো জল গ্যায়া\nপ্ররো রোশনি না হুই.........❤️\n\n\n✍️ {}"
    "আমি: দুনিয়া মে আইসি কেয়া চিজ হ্যায় জো ফ্রি মেই মিলতি হ্যায়............\nমাহ হৃদয়: ধোখা \n\n\n✍️ {}",
    "জো ইনসান আপকো তদাপতা হুয়া....রোটা চোর দে না........... তোহ সমাজ লেনা ও কাভি আপসে \nপ্যার নেই ক্রার স্কটা.....আগর কোন প্যায়ার করেগা না...। . .\nতো ও কাভি আপকো আইসে না ছোড়দেগা.......🥱🥱\n\n\n✍️ {}",
    "তোতে হ্যায়.....এস তারাহ দিল......\nআওয়াজ টিক না অ্যায়....\nহাম যায়ে যে রে হা.....\nকোই যে কে তো বাতায়ে....🙃🙃\ n\n\n✍️ {}",
    "আঁখোঁ মে আনসু লেকে........\nহোথন সে মুশকুরায়ে................\nহাম যাইসে জি রে হ্যায়.......\nক্লি জি কে তোহ BTAAE...🙃🙃\n\n\n✍️ {}",
    "তুঝে কায়সে পিটিএ না চালা.....................\nকে ম্যায় তেনু পেয়ার ক্রার দি আন............\nতুঝে কায়সে পিটিএ না চালা .. ....\nকে তেরা ইন্তেজার কেআরআর দি আনা........🙃\n\n\n✍️ {}",
    "এমটিটি চোরদনা কিসিকো উসকে হাল পে.......\nহো স্কটা হ.......\nআপকে আলাওয়া উসকে পাস অর কোই না হো.......🙃🙃\n\n\n✍️ {}",
    "🙂কেহতি হ্যায় জিন্দেগি পেয়ার কার কে তো দেখ,\n কেয়া পাতা থা জিস জিন্দগি নে পেয়ার মে জিনা শিখায়া,\n আজ ওয়াহি গির কে সামহালনা ভি শিখা গেই☺️\n\n\n✍️ {}",
    "আজ তোমার কথা মনে পড়লো..,\nঅশ্রু ঝরে পড়লো...,\nনদী নতুন বাঁক পেলো!!\n\n\n✍️ {}",
    "মাঝে মাঝে আমি বলতাম,\nআজ আমাকে শুরু করতে হবে...\n\nআমাদের সাথে কথা না বলার জন্য অজুহাত তৈরি করেছি। \n**বড় হতে...* \n\n\n✍️ {} ",
    "আমি জানি উত্তর দেওয়া সহজ নয় \nকিন্তু তুমি চেষ্টাও করো না,\nআমার অবস্থা জানার!!\n\n\n✍️ {}",
    "প্রতি বিচ্ছেদে আমরা খুঁজে পাই নতুন মিলন!!\nতোমাকে ছেড়ে বারবার চলে যাওয়াটা অভ্যাস হয়ে গেছে!!\n\n\n✍️ {}",
    "আমরা তখনও কোথায় ছিলাম যখন আমরা ভেবেছিলাম \nতুমি আমার হতে পারো না!!\nতুমি এখনো কোথায় বিশ্বাস করো\nতুমি কখনো আমার ছিলে!!\n\n\n✍️ {}",
    "সে পাগল,\nজানিনা কেন সে এত ভালবাসে!!\nআমি কিছু কথা বলার আগেই বুঝি!!\n\n\n✍️ {}",
    "আজকাল পরিস্থিতি \nটেলিফোন বুথের মতো হয়ে গেছে!\nলোকেরা এসে কথা বলে,\nআর শুধু চলে যায়!\n\n\n✍️ {}",
    "হৃদয় অনেক থামতে চায়\nকিন্তু থামবে না....!\nতুমি আমাদের কাছে কিছুই না\nআর আমরাও তোমার কাছে কিছুই না!!\n\n\n✍️ {}",
    "এটা আসলে কোন ব্যাপার না,\nকেউ আসে!\nশুধু হৃদয় যে বারবার অভ্যস্ত হয়ে যায়\n\nকেউ নেই..!!\nএটা থেকে মুক্তি পেতে একটু সময় লাগে!\n\n \n✍️ {}",
    "Not in mood. Sorry!!!!",
]

HFLIRT = [
    "Doctor Ne Advice Kia Hai Ki Sone Se Pahle Apki Pic Dekh Kar Sona Jaroori Hai, Warna Heart Attack Aa Sakta Hai.😨\n\n\n✍️ {}",
    "☺️Ap Itne Cute Ho Ki Agar Mai Msg Na Bhi Karna Chahu.To Bhi Mera Hath Khud Keypad Pr Chalne Lagta Hai😶.\n\n\n✍️ {}",
    "😋Aag joh dil mein lagi hai, usse duniya mein laga doonga main ... joh teri doli uthi, zamaane ko jalaa doonga main😏\n\n\n✍️ {}",
    "Jaldi se koi bhagwan ko bulao kyuki ek pari kho gayi hain aur wo pari yaha mujhse chatting kar rahi hain😛.\n\n\n✍️ {}",
    "Meri aankho 👀ko kuch ho gaya hain, aap per se hat hi nahi rahi hain😶\n\n\n✍️ {}",
    "🤨Aap choro ke rani lagte ho kyuki aapne mera dil chura liya hain😘\n\n\n✍️ {}",
    "👀Aapki aankhe ocean ki tarah blue he aur me usme har baar dub jata hu🙂\n\n\n✍️ {}",
    "📷Aap ek camera ki tarah ho jab bhi aapka photos dekhta hu meri automatic smile aaa jati hain🙈\n\n\n✍️ {}",
]

EFLIRT = [
    "Your lips look lonely would they like to meet mine?\n\n\n✍️ {}",
    "There isn’t a word in the dictionary to describe how beautiful you are\n\n\n✍️ {}",
    "I have had a really bad day and it always makes me feel better to see a pretty girl smile. So, would you smile for me?\n\n\n✍️ {}",
    "I lost my teddy bear can i sleep with you tonight?\n\n\n✍️ {}",
    "I’m no organ donor but I’d be happy to give you my heart.\n\n\n✍️ {}",
    "If I had to rate you out of 10 I’d rate you a 9… because I am the one that you are missing\n\n\n✍️ {}",
    "Can I follow you? Cause my mom told me to follow my dreams\n\n\n✍️ {}",
    "Your hand looks heavy can i hold it for you?\n\n\n✍️ {}",
    "You may fall from the sky, you may fall from a tree, but the best way to fall… is in love with me.\n\n\n✍️ {}",
    "Are you the sun? Because you’re so beautiful it’s blinding me\n\n\n✍️ {}",
    "I should call you Google, because you have everything I’m looking for.\n\n\n✍️ {}"
    "Can you kiss me on the cheek so I can at least say a cute girl kissed me tonight?\n\n\n✍️ {}",
]

ATTITUDE = [
    "দিল না করতা আব\n কিসি সে দিল লাগানে কো \n বোহোত আতি হ্যায় তেরে যায়সে \n কে দেতা হু হুঁ লাউত জানে কো।\n\n\n✍️ {}",
    "হামারি হেসিয়াত কা আন্দাজা তুম ইয়ে\n জান কে লাগা লো হাম কাভি আনকে \n নাহি হোতে জো হর কিসি কে হো জাতে হ্যায় \n\n\n✍️ {}",
    "মনোভাব আমার পরিবারও,\nআর তুমি আমার হৃদয়ের রানী,\nতাই বলছি মেনে নাও,\nকারণ তোমার কোটি কোটি মানুষ।\n\n\n✍️ {}",
    "আমার একজন আসবে একটু দেরিতে,\n কিন্তু যখন আসবে, লাখে একজন আসবে।\n\n\n✍️ {}",
    "জীবনে ভাগ্য বদলাতে থাকে এত মনোভাব না দেখিয়ে,\nআয়না থাকে,\nকিন্তু ছবি বদলায়।\n\n\n✍️ {}",
    "আমরা কালের, আমরা কালের নই,\nকেউ আমাদের দিকে তাকাবে,\nকারুর এত ক্ষমতা নেই।\n\n\n✍️ {}",
    "আমরা তলোয়ার পছন্দ করি,\nশিশুরা বন্দুকের উপর জোর দেয়।\nসিংহ নিজেরা শিকার করে এবং আমরা আমাদের মনোভাব নিয়ে আক্রমণ করি।\n\n\n✍️ {}",
    "সিংহ নিজেদের শিকার করে\n এবং আমরা আমাদের মনোভাব নিয়ে আক্রমণ করি।\n\n\n✍️ {}",
]

GBYE = [
    "জীবনে একা থাকা সম্ভব নয়,\nতোমার সাথে চলাফেরা করাটাও পৃথিবীর কাছে গ্রহণযোগ্য নয়,\nতাই তোমার থেকে দূরে যাওয়াই ভালো।\n\n\n✍️ {}",
    "কয়েকদিন একসাথে হাঁটছি,\nআরো একটু হাঁটতে ইচ্ছে করছে,\nআমাকে বিদায় জানাতে হবে।\n\n\n✍️ {}",
    "বলো না কিছু শুনিনি, শুধু চুপচাপ হেঁটে গেছি,\nসে ভালোবাসার সব মানে বদলে দিয়েছে,\nএখন প্রতিটা সন্ধ্যা কাটবে নির্জন রাস্তায়,\nমরে গেলেও তার নাম ভুলবে না।\n\n\n️ { }",
    "তুমি কাছে থাকলে কান্নার কারণ হতে,\nতুমি দূরে গিয়ে হাসতে শিখতে পারবে।\n\n\n✍️ {}",
    "জীবনে আবার দেখা হবে এই প্রার্থনা,\nদূরে থাকলেও কাছে থাকতে চাই।\n\n\n✍️ {}",
    "দুঃখিত আমাকে যেতে হবে বহুদূর,\nপাশ দিয়েও তোমাকে এখন ভুলে যেতে হবে।\n\n\n✍️ {}",
    "তোমাকে নিয়ে কেটেছে এক মনোরম সন্ধ্যা,\nতুমি ছাড়া সারা রাত কাটবে কি করে,\nবুঝবে তুমিও মনের বাধ্য,\nতুমি না গেলে কাল আবার দেখা হবে কি করে। n\n\n✍️ {}",
    "তোমার সাথে হাসতে হাসতে এবং হোঁচট সামলাতে,\nবিদায় জানাতে এসো না, থামতে শিখেছি।\n\n\n✍️ {}",
    "দোস্ত, তোমার বন্ধুত্বকে স্যালুট,\nবিদায় বলার পরেও হেসেছি,\nএটাই তোমার বন্ধুত্বের বিস্ময়।\n\n\n✍️ {}",
    "তোমার সাথে শেষ রাতগুলো আবার মনে পড়বে,\nতোমাকে বিদায় জানাতে পারি বন্ধু তাই,\nএক ফোঁটা চোখের জল না ফেলে তোমার সাথে কথা বলবো।\n\n\n✍️ {}",
    "জীবনের কঠিন সময়গুলোও ছিল রুক্ষ,\nতখন তোমার আর আমার মাঝের এই দূরত্বটা হারিয়ে গেল,\nতোমাকে বুঝতে হবে এটা আমার বাধ্যতা,\nনইলে তোমার আর আমার মধ্যে এই দূরত্ব আসত না।\n\n\ n✍️ {}",কাছে এসে তুমি একটু দূরে হয়ে গেছো,\nসন্ধ্যায় বিদায় নিয়ে,\nকোথাও হারিয়ে গেছো,\nআমি তোমার কাছে থাকার অনুভূতি চাই,\nআমি তোমাকে বিদায় জানিয়েছি সুখের জন্য। \n\n\n✍️ {}",
    "আমি খুশি তবুও এই চোখ ভিজে,\nআমি না চাইলেও চলে যাওয়াতে দুঃখ হয়।\n\n\n✍️ {}",
    "চলে যাওয়ার খবর শুনে মার থেমে যায়,\nবিদায় জানালে আমার চোখ জলে ভরে যায়।\n\n\n✍️ {}",
    "এখন প্রতিটা মুহূর্ত শূন্য মনে হবে তোমায় ছাড়া,\nবিদায় জানিয়ে বাঁচতে হবে তোমার স্মৃতিতে।\n\n\n✍️ {}",
    "এখন হৃদয়ে আলোড়ন উঠেছে নতুন আশার সন্ধানে,\nনতুন গন্তব্যের সন্ধানে বিদায় জানাতে হবে\n\n\n✍️ {}",
    "তুমি গেলে ঝরে যায় গুলিস্তানের সব ফুল,\nবিদায় বলো কেন, যেতে যেতে গাছে আছড়ে পড়ো।\n\n\n✍️ {}",
    "তিনি ধূর্ত চোখে যা দেখলেন,\nআমরা তন্দ্রাচ্ছন্ন হয়ে গেলাম,\nযখন আমরা জানতে পারলাম যে তিনি বিদায় জানাতে এসেছেন,\nআমরা অজ্ঞান হয়ে গেলাম।\n\n\n✍️ {}",
]
